name: Terraform CI/CD

on:
  push:
    paths:
      - '**.tf'  # Triggers when any Terraform file changes
  pull_request:
    paths:
      - '**.tf'  # Runs validation & plan on PRs

jobs:
  terraform:
    name: Terraform Apply on Code Change
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan

      - name: Apply Terraform Changes (Only on main)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
